### ISSUE TITLE
ThensorFlow SSE GPU not work

### ISSUE THREAD

**Issue by Expert73** [fo40225/tensorflow-windows-wheel#57]
ThensorFlow SSE GPU not work.
ThensorFlow AVX2 GPU on another computer with my model work fine.
Stats:
Limit:                   651931648
InUse:                   651866624
MaxInUse:                651931648
NumAllocs:                      94
MaxAllocSize:            160649216

2018-11-20 06:29:36.629859: W tensorflow/core/common_runtime/bfc_allocator.cc:27
1] *****************xxx******************xxx**********************************xx
xxxxx******************
2018-11-20 06:29:36.645459: W tensorflow/core/framework/op_kernel.cc:1273] OP_RE
QUIRES failed at concat_op.cc:153 : Resource exhausted: OOM when allocating tens
or with shape[33280] and type float on /job:localhost/replica:0/task:0/device:GP
U:0 by allocator GPU_0_bfc
Traceback (most recent call last):
  File "02_train_model_base_lstm_cudnn.py", line 119, in <module>
    verbose=1) #0,1,2
  File "G:\Py_SSE\WPy-3670_gpu\python-3.6.7.amd64\lib\site-packages\keras\engine
\training.py", line 1039, in fit
    validation_steps=validation_steps)
  File "G:\Py_SSE\WPy-3670_gpu\python-3.6.7.amd64\lib\site-packages\keras\engine
\training_arrays.py", line 199, in fit_loop
    outs = f(ins_batch)
  File "G:\Py_SSE\WPy-3670_gpu\python-3.6.7.amd64\lib\site-packages\keras\backen
d\tensorflow_backend.py", line 2715, in __call__
    return self._call(inputs)
  File "G:\Py_SSE\WPy-3670_gpu\python-3.6.7.amd64\lib\site-packages\keras\backen
d\tensorflow_backend.py", line 2675, in _call
    fetched = self._callable_fn(*array_vals)
  File "G:\Py_SSE\WPy-3670_gpu\python-3.6.7.amd64\lib\site-packages\tensorflow\p
ython\client\session.py", line 1439, in __call__
    run_metadata_ptr)
  File "G:\Py_SSE\WPy-3670_gpu\python-3.6.7.amd64\lib\site-packages\tensorflow\p
ython\framework\errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocat
ing tensor with shape[512,160,64] and type float on /job:localhost/replica:0/tas
k:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node embedding_1/embedding_lookup}} = GatherV2[Taxis=DT_INT32, Tind
ices=DT_INT32, Tparams=DT_FLOAT, _class=["loc:@training/Adam/Assign_2"], _device
="/job:localhost/replica:0/task:0/device:GPU:0"](embedding_1/embeddings/read, em
bedding_1/Cast, training/Adam/gradients/embedding_1/embedding_lookup_grad/concat
/axis)]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[{{node loss/mul/_91}} = _Recv[client_terminated=false, recv_device="/
job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replic
a:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_992_loss/
mul", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:
0"]()]]
Hint: If you want to see a list of allocated tensors when OOM happens, add repor
t_tensor_allocations_upon_oom to RunOptions for current allocation info.

**Comment by fo40225** [comment]
What is your GPU model?

Reduce your nn model or buy a new gpu with larger vram.

**Comment by Expert73** [comment]
I have CPU with only SSE2 instruction. My GPU - NVIDIA 650Ti.
i wrote my code 2 years ago. 

On older versions of the tensorflow that could be installed through the command pip install -thersorflow-gpu, everything worked perfectly.

I assume that the problem may be in the process of compiling thensorflow.

Some test:
1. CPU with only SSE2, GPU 650Ti, thensorflow for gpu sse2 - not work.
2. CPU with AVX2, GPU 650Ti, thensorflow for gpu sse2 - works fine.
3. CPU with AVX2, GPU 650 Ti, thensorflow for gpu avx2 - works fine.


What is old latest version of tensorflow officially supported sse2?

**Comment by fo40225** [comment]
@Expert73 `pip install tensorflow-gpu==1.5.0` is the latest version that support sse2 cpu.

**Comment by Expert73** [comment]
if I want to compile thensorflow myself on CPU with sse2. VS2015.
Need to install all the components? or can only individual?

**Comment by fo40225** [comment]
@Expert73  just follow https://www.tensorflow.org/install/source_windows

**Comment by Expert73** [comment]
Problem solved! The error was in the memory module on the motherboard.
Thanks for answers!
Last question: what edition of VS do you recommend for compiling a tensor flow?

**Comment by fo40225** [comment]
@Expert73 vs2015 is fine. 

vs2017 should work but not supported by official.
