### ISSUE TITLE
failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected

### ISSUE THREAD

**Issue by AliKhoda** [fo40225/tensorflow-windows-wheel#63]
Hi,

System: Windows 10 - miniconda
Installed cuda 10 & cudnn v7.4.1.5
rebooted after installation

I installed tensorflow_gpu-1.12.0-cp37-cp37m-win_amd64.whl

Error:
```
> python
Python 3.7.0 (default, Jun 28 2018, 08:04:48) [MSC v.1912 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tensorflow as tf
>>>
>>> class SquareTest(tf.test.TestCase):
...    def testSquare(self):
...      with self.test_session():
...        x = tf.square([2, 3])
...        self.assertAllEqual(x.eval(), [4, 9])
...
>>> if __name__ == '__main__':
...   tf.test.main()
...
2018-12-09 23:18:41.996479: E tensorflow/stream_executor/cuda/cuda_driver.cc:300] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2018-12-09 23:18:42.004053: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:163] retrieving CUDA diagnostic information for host: p04295
2018-12-09 23:18:42.014736: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:170] hostname: p04295
..
----------------------------------------------------------------------
Ran 2 tests in 0.064s

OK
```

```
> nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2018 NVIDIA Corporation
Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018
Cuda compilation tools, release 10.0, V10.0.130
```

```
> nvidia-smi
Sun Dec 09 23:28:21 2018
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 411.31                 Driver Version: 411.31                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 770    WDDM  | 00000000:02:00.0 N/A |                  N/A |
| 33%   32C    P8    N/A /  N/A |    116MiB /  4096MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+

+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0                    Not Supported                                       |
+-----------------------------------------------------------------------------+
```

Would you please let me know if I missed something in the installation? If not how to resolve this?

Best regards

**Comment by fo40225** [comment]
I haven't seen this error before.

Try set `CUDA_VISIBLE_DEVICES=0`

**Comment by AliKhoda** [comment]
I already tried that, it didn't make the error go away.
Can I provide you with more details?

**Comment by fo40225** [comment]
@AliKhoda Yes, you can.

**Comment by AliKhoda** [comment]
What would you like to know?

**Comment by AliKhoda** [comment]
I have 3 cuda versions installed, but the one in path is cuda 10.0.

**Comment by fo40225** [comment]
Run `C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery` and see if any error occur.

**Comment by AliKhoda** [comment]
Took some time to install VS community 2017:
error : Designtime build failed for project 'C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Set environment variable TRACEDESIGNTIME = true and restart Visual Studio to investigate.

**Comment by AliKhoda** [comment]
after setting TRACEDESIGNTIME:
```
error : Designtime build failed for project 'C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj' configuration 'Debug|x64'. IntelliSense might be unavailable.
	Check *.designtime.log files in your %TEMP% directory.
```

*.designtime.log:
```
Build started 10-Dec-18 1:42:56 PM.
Environment at start of build:
ALLUSERSPROFILE                = C:\ProgramData
APPDATA                        = C:\Users\Alikh\AppData\Roaming
CommonProgramFiles             = C:\Program Files (x86)\Common Files
CommonProgramFiles(x86)        = C:\Program Files (x86)\Common Files
CommonProgramW6432             = C:\Program Files\Common Files
COMPUTERNAME                   = P04295
ComSpec                        = C:\Windows\system32\cmd.exe
CUDA_PATH                      = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V10_0                = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
CUDA_PATH_V8_0                 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0
CUDA_PATH_V9_1                 = C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.1
DriverData                     = C:\Windows\System32\Drivers\DriverData
FPS_BROWSER_APP_PROFILE_STRING = Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING = Default
HOMEDRIVE                      = C:
HOMEPATH                       = \Users\Alikh
LOCALAPPDATA                   = C:\Users\Alikh\AppData\Local
LOGONSERVER                    = \\P04295
MSBuildLoadMicrosoftTargetsReadOnly = true
NUMBER_OF_PROCESSORS           = 4
NVCUDASAMPLES10_0_ROOT         = C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0
NVCUDASAMPLES8_0_ROOT          = C:\ProgramData\NVIDIA Corporation\CUDA Samples\v8.0
NVCUDASAMPLES9_1_ROOT          = C:\ProgramData\NVIDIA Corporation\CUDA Samples\v9.1
NVCUDASAMPLES_ROOT             = C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0
NVTOOLSEXT_PATH                = C:\Program Files\NVIDIA Corporation\NvToolsExt\
OneDrive                       = C:\Users\Alikh\OneDrive
OS                             = Windows_NT
Path                           = C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Apps\ffmpeg\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\Alikh\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\MATLAB\R2018b\runtime\win64;C:\Program Files\MATLAB\R2018b\bin;C:\Program Files\CMake\bin;C:\Program Files\Git\cmd;C:\Apps\youtubedl;C:\Program Files\NVIDIA Corporation\NVSMI;C:\Users\Alikh\AppData\Local\Programs\Python\Python37-32\Scripts\;C:\Users\Alikh\AppData\Local\Programs\Python\Python37-32\;C:\Users\Alikh\AppData\Local\Microsoft\WindowsApps;
PATHEXT                        = .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC
PkgDefApplicationConfigFile    = C:\Users\Alikh\AppData\Local\Microsoft\VisualStudio\15.0_197f46e1\devenv.exe.config
PROCESSOR_ARCHITECTURE         = x86
PROCESSOR_ARCHITEW6432         = AMD64
PROCESSOR_IDENTIFIER           = Intel64 Family 6 Model 37 Stepping 2, GenuineIntel
PROCESSOR_LEVEL                = 6
PROCESSOR_REVISION             = 2502
ProgramData                    = C:\ProgramData
ProgramFiles                   = C:\Program Files (x86)
ProgramFiles(x86)              = C:\Program Files (x86)
ProgramW6432                   = C:\Program Files
PROMPT                         = $P$G
PSModulePath                   = C:\Program Files\WindowsPowerShell\Modules;C:\Windows\system32\WindowsPowerShell\v1.0\Modules
PUBLIC                         = C:\Users\Public
SESSIONNAME                    = Console
SystemDrive                    = C:
SystemRoot                     = C:\Windows
TEMP                           = C:\Users\Alikh\AppData\Local\Temp
TMP                            = C:\Users\Alikh\AppData\Local\Temp
TRACEDESIGNTIME                = true
USERDOMAIN                     = P04295
USERDOMAIN_ROAMINGPROFILE      = P04295
USERNAME                       = Alikh
USERPROFILE                    = C:\Users\Alikh
VisualStudioDir                = C:\Users\Alikh\Documents\Visual Studio 2017
VisualStudioEdition            = Microsoft Visual Studio Community 2017
VisualStudioVersion            = 15.0
VS140COMNTOOLS                 = C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\Tools\
VSAPPIDDIR                     = C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\
VSAPPIDNAME                    = devenv.exe
vsconsoleoutput                = 1
VSLANG                         = 1033
VSSKUEDITION                   = Community
windir                         = C:\Windows

Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Trying to import C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props using extensions path C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild
Property reassignment: $(MSBuildProjectExtensionsPath)="C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\obj\" (previous value: "obj\") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Microsoft.Common.props (60,5)
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Trying to import C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore\* using extensions path C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Property reassignment: $(PlatformToolset)="v100" (previous value: "") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\Platform.default.props (26,5)
Property reassignment: $(MSBuildAllProjects)=";C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.targets;C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj.user" (previous value: ";C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.targets") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props (166,5)
Property reassignment: $(PlatformToolset)="v141" (previous value: "v100") at C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj (26,5)
Property reassignment: $(_PlatformFolder)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\\Platforms\x64\") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\Platform.props (15,5)
Property reassignment: $(TargetExt)=".exe" (previous value: "") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Common.props (29,5)
Property reassignment: $(VC_IncludePath)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\include;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\include" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\include;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (17,5)
Property reassignment: $(VC_LibraryPath_x86)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x86;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x86;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\lib" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x86;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x86;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (19,5)
Property reassignment: $(VC_LibraryPath_x64)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x64;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\lib" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x64;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (20,5)
Property reassignment: $(VC_LibraryPath_ARM)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\ARM;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\arm;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\lib" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\ARM;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\arm;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (21,5)
Property reassignment: $(_PropertySheetDisplayName)="Multi-byte Character Support" (previous value: "Core Windows Libraries") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.MultiByteCharSupport.props (15,5)
Property reassignment: $(_PropertySheetDisplayName)="Application" (previous value: "Multi-byte Character Support") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Application.props (15,5)
__________________________________________________
Project "C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj" (GetClCommandLines;GetGeneratedFiles;GetProjectReferencesInfo target(s)):

Building with tools version "15.0".
C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj(37,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Done building project "deviceQuery_vs2017.vcxproj" -- FAILED.
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Trying to import C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\$(MSBuildToolsVersion)\Microsoft.Common.props using extensions path C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild
Property reassignment: $(MSBuildProjectExtensionsPath)="C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\obj\" (previous value: "obj\") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Microsoft.Common.props (60,5)
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Trying to import C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\$(MSBuildToolsVersion)\Imports\Microsoft.Common.props\ImportBefore\* using extensions path C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Search paths being used for $(MSBuildExtensionsPath) are C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild;$(MSBuildProgramFiles32)\MSBuild
Property reassignment: $(PlatformToolset)="v100" (previous value: "") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\Platform.default.props (26,5)
Property reassignment: $(MSBuildAllProjects)=";C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.targets;C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj.user" (previous value: ";C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\MSBuild\15.0\Bin\Microsoft.Common.targets") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Default.props (166,5)
Property reassignment: $(PlatformToolset)="v141" (previous value: "v100") at C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj (26,5)
Property reassignment: $(_PlatformFolder)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\\Platforms\x64\") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Platforms\x64\Platform.props (15,5)
Property reassignment: $(TargetExt)=".exe" (previous value: "") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Common.props (29,5)
Property reassignment: $(VC_IncludePath)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\include;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\include" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\include;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\include;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.15063.0\ucrt;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (17,5)
Property reassignment: $(VC_LibraryPath_x86)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x86;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x86;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\lib" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x86;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x86;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x86;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (19,5)
Property reassignment: $(VC_LibraryPath_x64)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x64;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\lib" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\x64;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\x64;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\x64;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (20,5)
Property reassignment: $(VC_LibraryPath_ARM)="C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\ARM;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\arm;;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\UnitTest\lib" (previous value: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Tools\MSVC\14.16.27023\atlmfc\lib\ARM;;C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\VS\lib\ARM;;C:\Program Files (x86)\Windows Kits\10\lib\10.0.15063.0\ucrt\arm;;") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.UnitTest.props (21,5)
Property reassignment: $(_PropertySheetDisplayName)="Multi-byte Character Support" (previous value: "Core Windows Libraries") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.MultiByteCharSupport.props (15,5)
Property reassignment: $(_PropertySheetDisplayName)="Application" (previous value: "Multi-byte Character Support") at C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.Cpp.Application.props (15,5)
__________________________________________________
Project "C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj" (GetProjectDirectories target(s)):

Building with tools version "15.0".
C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj(37,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

Done building project "deviceQuery_vs2017.vcxproj" -- FAILED.

Project Evaluation Performance Summary:
        * ms  C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj   1 calls
        (* = timing was not recorded because of reentrancy)

Project Performance Summary:
       64 ms  C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj   2 calls

Build FAILED.

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj(37,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\deviceQuery_vs2017.vcxproj(37,5): error MSB4019: The imported project "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\BuildCustomizations\CUDA 10.0.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
    0 Warning(s)
    2 Error(s)

Time Elapsed 00:00:00.94
```

**Comment by AliKhoda** [comment]
Got the same error from the sample test!
```
C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\../../bin/win64/Debug/deviceQuery.exe Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

cudaGetDeviceCount returned 38
-> no CUDA-capable device is detected
Result = FAIL

C:\ProgramData\NVIDIA Corporation\CUDA Samples\v10.0\1_Utilities\deviceQuery\../../bin/win64/Debug/deviceQuery.exe (process 10540) exited with code 1.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.
Press any key to close this window . . .
```

**Comment by AliKhoda** [comment]
Reinstalling and restart did not help. Getting the same error.
Trying a wheel for another CUDA version.

**Comment by AliKhoda** [comment]
Seems like there is a problem with the newer driver and has nothing to do with this package. Posted to
[nvidia devtalk](https://devtalk.nvidia.com/default/topic/989802/cuda-setup-and-installation/geforce-gtx-770-supported-by-cuda-8-0-/)

**Comment by AliKhoda** [comment]
Reverted to CUDA 9.1 and the driver that comes with it.
tensorflow_gpu-1.8.0-cp36-cp36m-win_amd64 works like a charm.

**Comment by clhne** [comment]
some issue.
solution:
export CUDA_VISIBLE_DEVICES=0

**Comment by olegtropinin** [comment]
I set CUDA_VISIBLE_DEVICES to -1 and 0. It do not help me.

**Comment by dtlam26** [comment]
> I set CUDA_VISIBLE_DEVICES to -1 and 0. It did not help me.

-1 is disabling GPU. Why did you set that? You should set the env to see the corresponding index of GPU in nvidia-smi

**Comment by dtlam26** [comment]
For me, the problem starts with the loading dataset in tfds. Therefore, I just need to load it right when I call the tfds import. And everything backs to normal
